### PR TITLE
Add instructions for cluster-detect script

### PR DESCRIPTION
**Pull request by ctlong**
Co-authored-by: Carson Long <lcarson@vmware.com>
Co-authored-by: Renee Chu <reneec@vmware.com>

[#175067724] Alana invokes a separate script to detect 3rd party JWT support

### CODE REVIEW

**Comment by ctlong** [comment]
Depends on https://github.com/pivotal/tanzu-application-service/pull/341/files

**Comment by ograves-pivotal** [comment]
@ctlong @reneighbor 
Docs here. Just confirming:
 - You added this step to _Install TAS for Kubernetes from the VMware Tanzu Network_. Is this step needed for the _Install TAS for Kubernetes from a Private System Registry_ section?
 - I've modified your revision into the terse docs style. Please confirm I haven't lost your intended meaning:
    _3. To create a cluster configurations file:_
    ...
    _The `cluster-detect` script communicates with the kube API to determine deployment values and saves those values in a `cluster-values` configuration file._

**Comment by ctlong** [comment]
Hey @ograves-pivotal!
* Good catch. It looks like this step should in fact be included in the _Install TAS for Kubernetes from a Private System Registry_ section. I'll make a separate PR for that.
* Those changes look fine to me. I don't see them reflected in this PR though?

**Comment by ograves-pivotal** [comment]
Thanks, @ctlong !

**Comment by ctlong** [comment]
Created the new PR here: https://github.com/pivotal-cf/docs-tas-kubernetes/pull/56

**Pull request merged**
