### PR TITLE
Add documentation for fetching the version

### PR DESCRIPTION
**Pull request by julian-hj**
- adds instructions to fetch the version of a TAS for K8s deployment

Authored-by: Julian Hjortshoj <hjortshojj@vmware.com>

[#174204370] Add documentation for Alana to learn the version of her TAS for K8s deployment

### CODE REVIEW

**Comment by julian-hj** [comment]
@ograves-pivotal The feature documented here is also available in the upcoming 0.4 release, so this docs change can go in the 0.4 branch as well, if we have already cut that branch. Let me know if you prefer a separate PR for that.

**Comment by seviet** [comment]
@julian-hj thanks for the PR!! quick question-- in the context of this procedure, do you consider checking the tas-for-k8s version on a cluster as part of the validating the tas-for-k8s installation? if so, i would make this addition an H3 and part of the above section rather than an H2 and separate. also do you have some output with the actual values? wondering what the user might expect to see in terms of `buildnumber`. thanks!

**Comment by julian-hj** [comment]
Hi @seviet 
No, I wasn't thinking of it as part of the validation. It's more of an administration/troubleshooting task, but the current administering page doesn't have anything similar, so I just put it in the best place I could find. Please feel free to move it if there's somewhere better you can find.

Regarding the actual version numbers, the real data will look something like this:
```
data:
  commit: 53ad0edd093dbad71debc193541b5c6f0b2b094d
  version: 0.4.0-build.57
```

Or, in the format that the user would see it after running the suggested command:
```
map[commit:53ad0edd093dbad71debc193541b5c6f0b2b094d version:0.4.0-build.57]
```

**Comment by seviet** [comment]
Thanks! I think it might make sense to move this content eventually to the "Administering" section-- or perhaps we need to start a "Troubleshooting" topic for this doc set. However, this particular piece is so small right now I don't know if it deserves a brand new topic yet. I'll create a docs story for the move. Also perhaps also @ograves-pivotal has an opinion on where it should finally live.

**Pull request merged**
